version: 2.1

workflows:
  first-workflow:
    jobs:
      - first-job

jobs:
  first-job:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run: mkdir test-reports
#      - run:
#          name: Download Selenium
#          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
#      - run:
#          name: Start Selenium
#          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
#          background: true
      - run:
           name: Install Chrome
           command: |
                  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                  echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
                  sudo apt-get update && sudo apt-get install -y google-chrome-stable

           # Install dependencies
      - run: mvn dependency:resolve

            # Build the project without running tests
      - run: mvn clean install

            # Run Selenium TestNG tests
#      - run: mvn test
      - run:
          name: Run specific tests
          command: "mvn clean test -DsuiteXmlFile=sanity.xml -PSanity"
